server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      # 这三个值都是默认值
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://106.12.92.100:3306/payment?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qq498423089

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.candy.cloud.entity
